EMAIL_ID = "email"
PASSWORD_ID = "passwd"
SIGN_IN_BTN_ID = "SubmitLogin"
LOGIN_FAILURE_MESSAGE_XPATH = "//li[contains(text(),'Authentication failed.')]"
MY_ACCOUNT_TEXT = "//span[text()='My account']"
